### ISSUE TITLE
Date comparison in testRFC2822 fails.

### ISSUE THREAD

**Issue by BennettSmith** [royratcliffe/ActiveSupportKit#1]
The `NSDate` constructed on [line 150](https://github.com/royratcliffe/ActiveSupportKit/blob/master/ActiveSupportKitTests/ActiveSupportKitTests.m#L150) is reported by Xcode to have a timezone of PST even though it was constructed using a calendar with EST as the timezone.  

The `NSDateComponents` used to prepare the date should result in a value of:

> 1999-12-31 19:00:00 EST

But, the actual value constructed is:

> 1999-12-31 16:00:00 PST

That date is then passed into the `ASRFC2822StringFromDate` method which returns:

> 31 Dec 1999 16:00 -0800

The value expected in the `STAssertEqualObjects` test is:

> 01 Jan 2000 00:00 +0000

Something is wrong with how the timezone is being treated. All three values are equivalent, but the test seems to be expecting some sort of timezone conversion to take place.

**Comment by BennettSmith** [comment]
You can see the results of a Jenkins build here:

http://ci.focalshift.com:8085/job/ActiveSupportKit/lastCompletedBuild/testReport/

Note that the build is for the LevideCapital repo, not the royratcliffe repo.

**Comment by royratcliffe** [comment]
The test mistakenly assumes GMT for the default time zone. The update (version 1.5) compares the RFC-2822 date with a date string based on the current system time zone.
